\input texinfo
@setfilename doc.info
@documentencoding UTF-8

@settitle 3D Viewer

@copying
Copyright © 2022 Mikhail Rudnev, Julia Rudneva & Evgeny Berezny
@end copying


@titlepage
@title 3D Viwer v1.0
@insertcopying
@end titlepage

@contents

@ifnottex
@node Top
@end ifnottex

@node 3D Viewer
@chapter 3D Viewer

@cindex intro
Приложение 3D Viewer отрисовывает obj-файлы, создавая модели на OpenGL.

Укажите локальный файл для открытия.

Поддерживается перемещение моделей по осям X, Y и Z, а также увеличение и вращение моделей.

В приложении реализована возможность настройки цветов для отрисовки вершин и граней, а так же для основного фона.

Кроме того, реализована возможность изменять форму вершин и характер линий для отрисовки 3D модели.

Приложеине автоматически сохраняет выбранные пользователем настройки для вывода изображения, которые при следующем запуске программы можно применить, нажав на кнопку "Вернуть настройки".

@node Экспорт картинок
@chapter Экспорт картинок

Приложение сохраняет статичные скриншоты в форматах *.bmp и *.jpeg.

Также можно сохранить анимированную картинку в формате *.gif.

@printindex cp

@bye